name: Manual Format RSS
description: Manually run 
on:
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  setup_clash:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # 检出代码仓库

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run CNfetch.py script
        shell: bash
        working-directory: ${{ github.action_path }}
        run: |
          python3 ./add_follow_info.py

      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          repository: Stream-L/rss_publisher
          ref: main
          token: ${{ secrets.TARGET_REPO_TOKEN }}
          path: target-repo

      - name: Copy RSS files to target repository
        uses: actions/upload-artifact@v3

      - name: Commit and push changes
        working-directory: target-repo
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ secrets.EMAILADDRESS }}"
          git add feeds/ rss_links.txt
          if [[ -n $(git status --porcelain) ]]; then
            git commit -m "Update RSS feeds and links"
            git push origin main
          else
            echo "No changes to push."
          fi

